backend:
  name: git-gateway
  branch: main  # Branch to edit (default is main)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections:
  - name: "post" # Name of the collection
    label: "Post" # Label for the collection
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
