backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "homepage"
    label: "Home Page"
    files:
      - label: "Main Content"
        name: "home"
        file: "/Users/calebrouse/Documents/backupwebsite/index.html"
        fields:
          - { label: "B-Roll Image", name: "b_roll_image", widget: "image" }
          - { label: "Video Text 1", name: "video_text_1", widget: "string" }
          - { label: "Video Text 2", name: "video_text_2", widget: "string" }

          - label: "Carousel Items"
            name: "carousel"
            widget: "list"
            fields:
              - { label: "Image", name: "carousel_image", widget: "image" }




